### ISSUE TITLE
Parameter passed in QueryString named paymentType

### ISSUE THREAD

**Issue by pierrebaran** [polyright/PaymentTerminal-URI-Scheme#6]
At the moment, the paymentType parameter is set to either    Twint  or Epurse

For clarity purposes, the Epurse parameter should be name Polyright

Discussed with @sverleye .

**Comment by YZahringer** [comment]
I agree. But the parameter in the polyright API is called Epurse. I think we should keep the same name.

**Comment by sverleye** [comment]
As this value is used in all our devices and module, we will keep it unchanged. I'll adapt slightly the documentation.
